fleet_subdomain      = "fleet.example.com"
fleet_license_key    = "replace-with-real-license-key"
cloudflare_api_token = "replace-with-scoped-cloudflare-token"
cloudflare_zone_name = "example.com"
budget_alert_email   = "REPLACE_WITH_ALERT_EMAIL"
waf_ci_header_value  = "replace-with-output-of-openssl-rand-hex-32"
